### ISSUE TITLE
#TK01 Definir Scrum Master inicial y registrarse cada integrante faltante dentro del repositorio a trabajar

### ISSUE THREAD

**Issue by PaoTes** [TecnoXpress/TecnoXpress-ISPC-24#1]
**Srum Master:** Andrea Paola Testa

**Comment by CarolinaV22** [comment]
Carolina Valles, DeveloperTeam.

**Comment by Francovega** [comment]
Vega Franco Daniel, equipo de desarrolladores.

**Comment by rosrob** [comment]
Romina Robledo, Developer Team.

**Comment by valentachini** [comment]
Valentina Tachini, developer team.

**Comment by RominaTejeda** [comment]
Tejeda Romina Soledad, Developer Team

**Comment by TauTech99** [comment]
SAIDI Taoufik: developer team
