### ISSUE TITLE
#TK011 Crear un superusuario para poder realizar un CRUD utilizando la herramienta Admin de Django

### ISSUE THREAD

**Issue by PaoTes** [TecnoXpress/TecnoXpress-ISPC-24#12]

**Comment by Francovega** [comment]
Tarea terminada 
Para acceder al perfil de administrador de Django tendran los siguientes super usuarios
Para los profes
Usuario: ProfesISPC
Contraseña: admin

Para los desarrolladores 
Usuario: desarrolladores
Contraseña: admin
