### ISSUE TITLE
#TK02 Revisar y actualizar documento IEEE830. Editarlo en linea en Word. 

### ISSUE THREAD

**Issue by PaoTes** [TecnoXpress/TecnoXpress-ISPC-24#2]
Cuando esté listo se guarda en PDF para subir al repositorio

**Comment by eriRo-DBContext** [comment]
Hola Team acá adjunto  captura de pantalla del google.doc. Lo que me tocaba actualizar de la documentación: Requisitos Específicos y las Historias de Usuario. Saludos a todos.

![requisitosEspecificos](https://github.com/TecnoXpress/TecnoXpress-ISPC-24/assets/130596366/92a7591c-2ab4-44cd-ae0b-3fd9bfd9279a)
![historiasUsuario](https://github.com/TecnoXpress/TecnoXpress-ISPC-24/assets/130596366/e33201c7-2e09-4872-a856-bb1e0338f251)

**Comment by PaoTes** [comment]
**Documentacion IEEE830** 
Actualización de Rol dentro del Equipo de trabajo.

![Image](https://github.com/TecnoXpress/TecnoXpress-ISPC-24/assets/89785287/56f301ab-5278-49f6-b42e-81e814dba310)

**Comment by Francovega** [comment]
Se agrego nuevos lenguajes y frameworks en la sección de restricciones del documento, además se debe tener en cuenta una restricción mas,
