### ISSUE TITLE
#TK04 Plantear historias de usuarios (US) y Tareas (TK) dependientes de las US para incorporarlas en el repositorio remoto GitHub.

### ISSUE THREAD

**Issue by PaoTes** [TecnoXpress/TecnoXpress-ISPC-24#4]

**Comment by eriRo-DBContext** [comment]
Erica Robledo me asigno la #US15 Checkout en la cuál se desprenden las siguientes tareas de manera inicial (que pueden ampliarse en el futuro):

1. Creación de componentes de Angular
2. Inyección de servicios de Angular
3. Creación de modelos y formularios en Django
4. Formulario reactivo en Angular.
5. Operaciones de Guardado de datos ingresados en Base de Datos con Django.
